[package]
authors = ["Sergey Potapov <blake131313@gmail.com>"]
build = "build.rs"
edition = "2021"
name = "yasec_test_suite"
version = "1.1.2"

[dependencies]
bytesize = "1.1.0"
humantime = "2.1.0"
yasec = {path = "../"}

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
skeptic = "0.13"
